[package]
name = "cputray"
version = "0.5.0"
authors = ["Artemov Ivan  <zoxexivo@gmail.com>"]
edition = "2018"

[dependencies]
cpu-monitor = "0.1.1"
imageproc = "0.21.0"
image = "0.23.10"
rusttype = "0.9.2"
[target.'cfg(windows)'.dependencies]
winapi = { version = "*", features = ["winuser","wincon","shellapi"] }
