[package]
name = "cputray"
version = "0.3.0"
authors = ["Artemov Ivan  <zoxexivo@gmail.com>"]
edition = "2018"

[dependencies]
cpu-monitor = "0.1.1"
imageproc = "0.19.2"
image = "0.22.3"
rusttype = "0.8.1"
[target.'cfg(windows)'.dependencies]
winapi = { version = "*", features = ["winuser","wincon","shellapi"] }
